# Generated by Django 4.0.6 on 2022-07-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laere', '0002_event_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
